/**
 * Source list for content/catalog.json (AU naming).
 * Format: "Name | alias, alias | @TheMealDB Ingredient" — aliases and image override are optional.
 * Run `pnpm catalog:build` after editing.
 */
export const CATALOG_SEED: Record<string, string[]> = {
  "fruit-veg": [
    "Apple | apples, pink lady apple, granny smith apple | @Apples",
    "Banana | bananas",
    "Orange | oranges",
    "Mandarin | mandarins",
    "Lemon | lemons",
    "Lime | limes",
    "Pear | pears | @Pears",
    "Grapes | green grapes, red grapes",
    "Strawberries | strawberry",
    "Blueberries | blueberry",
    "Raspberries | raspberry",
    "Mango | mangoes",
    "Pineapple | pineapple slices, pineapple rings",
    "Watermelon",
    "Rockmelon | cantaloupe",
    "Kiwi Fruit | kiwi, kiwifruit",
    "Peach | peaches | @Peaches",
    "Nectarine | nectarines",
    "Plum | plums",
    "Cherries | cherry | @Cherry",
    "Passionfruit",
    "Avocado | avocados, avo",
    "Tomato | tomatoes | @Tomatoes",
    "Cherry Tomatoes | cherry tomato, grape tomatoes",
    "Truss Tomatoes | vine tomatoes, tomatoes on the vine | @Vine Tomatoes",
    "Roma Tomatoes | plum tomatoes | @Plum Tomatoes",
    "Brown Onion | onion, onions, brown onions | @Onions",
    "Red Onion | red onions, spanish onion | @Red Onions",
    "Spring Onion | spring onions, scallions, green onion | @Spring Onions",
    "Eschalot | eschalots, french shallot, french shallots, shallot, shallots | @Shallots",
    "Garlic | garlic bulb, garlic clove, garlic cloves",
    "Ginger | fresh ginger, ginger root",
    "Potato | potatoes, white potatoes, brushed potatoes | @Potatoes",
    "Baby Potatoes | chat potatoes, new potatoes | @Small Potatoes",
    "Sweet Potato | sweet potatoes, kumara",
    "Carrot | carrots | @Carrots",
    "Broccoli | broccoli head, broccoli florets",
    "Broccolini | baby broccoli | @Chinese Broccoli",
    "Cauliflower | cauliflower florets",
    "Zucchini | zucchinis, courgette, zucchini squash",
    "Eggplant | eggplants, aubergine | @Aubergine",
    "Red Capsicum | capsicum, red pepper, bell pepper | @Red Pepper",
    "Green Capsicum | green pepper | @Green Pepper",
    "Yellow Capsicum | yellow pepper | @Yellow Pepper",
    "Cucumber | cucumbers, continental cucumber, lebanese cucumber",
    "Iceberg Lettuce | lettuce, iceberg | @Lettuce",
    "Cos Lettuce | romaine, baby cos, romaine hearts, romaine lettuce, romaine heart | @Little Gem Lettuce",
    "Mixed Salad Leaves | salad leaves, mesclun, mixed leaves, mixed salad, gourmet leaf mix, spring mix, spring mix mixed greens | @Lettuce",
    "Spinach & Rocket Mix | spinach and rocket | @Spinach",
    "Coleslaw Mix | slaw mix, shredded cabbage mix, salad slaw, broccoli slaw | @Cabbage",
    "Deluxe Salad Mix | salad mix | @Lettuce",
    "Asian Greens | choy sum, gai lan | @Chinese Broccoli",
    "Kumato | kumato tomatoes | @Tomatoes",
    "Baby Spinach | spinach, spinach leaves | @Spinach",
    "Rocket | arugula, baby rocket, rocket leaves",
    "Kale",
    "Cabbage | green cabbage, savoy cabbage",
    "Red Cabbage | purple cabbage | @Cabbage",
    "Wombok | chinese cabbage, napa cabbage | @Cabbage",
    "Bok Choy | pak choy, baby bok choy",
    "Celery",
    "Mushrooms | button mushrooms, cup mushrooms | @Mushrooms",
    "Swiss Brown Mushrooms | cremini, chestnut mushrooms | @Chestnut Mushroom",
    "Shiitake Mushrooms",
    "Green Beans | beans, french beans",
    "Snow Peas | mangetout | @Sugar Snap Peas",
    "Sugar Snap Peas | pea pods",
    "Corn Cob | corn, sweetcorn, corn on the cob | @Sweetcorn",
    "Pumpkin | butternut pumpkin, kent pumpkin, butternut squash | @Butternut Squash",
    "Beetroot | beets",
    "Leek | leeks",
    "Asparagus",
    "Brussels Sprouts",
    "Fennel | fennel bulb",
    "Parsnip | parsnips",
    "Radish | radishes",
    "Bean Sprouts | beansprouts",
    "Long Red Chilli | chilli, red chilli, fresh chilli | @Red Chilli",
    "Green Chilli | jalapeno | @Green Chilli",
    "Coriander | cilantro, fresh coriander",
    "Flat-Leaf Parsley | parsley, italian parsley | @Parsley",
    "Basil | fresh basil, basil leaves",
    "Mint | fresh mint, mint leaves",
    "Sage | fresh sage, sage leaves",
    "Turnip | turnips | @Turnips",
    "Soffritto Mix | soffritto, mirepoix | @Celery",
    "Dill | fresh dill",
    "Chives | fresh chives",
    "Thyme | fresh thyme",
    "Rosemary | fresh rosemary",
    "Lemongrass | lemon grass",
    "Kaffir Lime Leaves | makrut lime leaves, lime leaves",
    "Snacking Cucumbers | qukes",
    "Silverbeet | swiss chard, chard",
    "Fioretto | fioretto cauliflower",
    "Carrot & Zucchini Mix",
    "Yellow Squash | summer squash",
    "Spaghetti Squash",
    "Acorn Squash",
    "Alfalfa Sprouts | alfalfa",
    "Apricot | apricots | @Apricot",
    "Blackberries | blackberry | @Blackberries",
    "Grapefruit | grapefruits | @Grapefruit",
  ],
  "meat-seafood": [
    "Chicken Breast | chicken breasts, chicken breast fillet | @Chicken Breast",
    "Chicken Thigh | chicken thighs, chicken thigh fillets | @Chicken Thighs",
    "Chicken Drumsticks | drumsticks | @Chicken Legs",
    "Chicken Tenderloins | chicken tenders",
    "Whole Chicken | chicken | @Chicken",
    "Chicken Mince | ground chicken",
    "Beef Mince | mince, ground beef, minced beef | @Minced Beef",
    "Pork Mince | ground pork, minced pork | @Minced Pork",
    "Lamb Mince | ground lamb",
    "Turkey Mince | ground turkey",
    "Beef Steak | steak, scotch fillet, sirloin, rump steak | @Beef Fillet",
    "Beef Strips | stir-fry beef, beef stir fry",
    "Diced Beef | chuck steak, gravy beef | @Beef",
    "Beef Brisket",
    "Pork Chops | pork cutlets | @Pork",
    "Pork Belly",
    "Pork Fillet | pork tenderloin | @Pork",
    "Lamb Chops | lamb cutlets | @Lamb Loin Chops",
    "Lamb Leg | leg of lamb",
    "Lamb Shoulder",
    "Lamb Rump | lamb rumps | @Lamb",
    "Beef Eye Fillet | eye fillet | @Beef Fillet",
    "Sausages | snags, beef sausages, pork sausages",
    "Italian Sausages | @Italian Fennel Sausages",
    "Bacon | rashers, bacon rashers, short cut bacon",
    "Chorizo",
    "Salmon Fillet | salmon, salmon fillets, skin-on salmon | @Salmon",
    "Barramundi Fillet | barramundi | @White Fish Fillets",
    "White Fish Fillet | basa, hoki, white fish | @White Fish Fillets",
    "Prawns | king prawns, peeled prawns | @King Prawns",
    "Tuna Steak | @Tuna",
    "Mussels",
    "Squid | calamari",
  ],
  deli: [
    "Ham | sliced ham, leg ham",
    "Prosciutto",
    "Salami",
    "Shaved Turkey",
    "Hummus | houmous",
    "Falafel | falafels, spinach falafel",
    "Tzatziki | tzatziki sauce",
    "Olives | kalamata olives, black olives | @Black Olives",
    "Green Olives",
    "Semi-Dried Tomatoes | sun-dried tomatoes | @Sun-Dried Tomatoes",
    "Marinated Feta",
    "Dips",
    "Plant-Based Mince | veggie ground, veggie mince, meatless mince, plant based mince",
    "Plant-Based Burger Patty | veggie burger patties, veggie burger patty, plant based burger patties, veggie patties",
    "Kimchi | plant-based kimchi",
    "Guacamole",
    "Fresh Tortellini | cheese tortellini, tortellini",
    "Fresh Ravioli | cheese ravioli, ravioli",
  ],
  "dairy-eggs": [
    "Milk | full cream milk, whole milk | @Milk",
    "Skim Milk | light milk | @Semi-skimmed Milk",
    "Oat Milk",
    "Almond Milk",
    "Soy Milk | @Soya Milk",
    "Eggs | egg, free range eggs | @Eggs",
    "Butter | salted butter | @Butter",
    "Unsalted Butter",
    "Thickened Cream | cream, whipping cream, heavy cream | @Double Cream",
    "Cooking Cream | light cooking cream | @Single Cream",
    "Sour Cream | light sour cream",
    "Cream Cheese | philadelphia",
    "Creme Fraiche",
    "Greek Yoghurt | greek yogurt, natural yoghurt, plain yoghurt | @Greek Yogurt",
    "Yoghurt | yogurt, flavoured yoghurt | @Yogurt",
    "Cheddar Cheese | tasty cheese, cheddar, shredded cheese, grated cheese | @Cheddar Cheese",
    "Mozzarella | mozzarella cheese, shredded mozzarella, buffalo mozzarella, buffalo mozarella",
    "Parmesan | parmesan cheese, grated parmesan, parmigiano | @Parmesan",
    "Feta | fetta, feta cheese, fetta cheese, crumbled feta, fetta cubes, feta cubes",
    "Haloumi | halloumi",
    "Ricotta | ricotta cheese",
    "Paneer | paneer cheese",
    "Mascarpone",
    "Goat's Cheese | goats cheese, chevre | @Goats Cheese",
    "Brie",
    "Bocconcini | @Mozzarella Balls",
    "Sliced Cheese | cheese slices | @Cheese",
    "Custard",
    "Blue Cheese | crumbled blue cheese, blue cheese crumbles",
    "Cottage Cheese",
  ],
  bakery: [
    "Bread | sliced bread, sandwich bread, white bread",
    "Wholemeal Bread | wholegrain bread, multigrain bread | @Wholegrain Bread",
    "Sourdough | sourdough loaf | @Crusty Bread",
    "Bread Rolls | rolls, burger buns, brioche buns, bake-at-home buns, buns",
    "Hot Dog Rolls",
    "Wraps | tortillas, flour tortillas, mini wraps | @Flour Tortilla",
    "Corn Tortillas",
    "Pita Bread | pita, pocket bread",
    "Flatbread | flatbreads, mini flatbreads | @Naan Bread",
    "Naan | naan bread | @Naan Bread",
    "Turkish Bread",
    "Baguette | french stick",
    "Ciabatta | ciabatta roll, bake-at-home ciabatta | @Crusty Bread",
    "Croissants",
    "Bagels",
    "English Muffins | crumpets",
    "Pizza Bases | pizza base, wholemeal pizza bases, pizza dough",
  ],
  pantry: [
    "Olive Oil | extra virgin olive oil, evoo | @Olive Oil",
    "Vegetable Oil | canola oil, cooking oil | @Vegetable Oil",
    "Sesame Oil | sesame oil blend | @Sesame Seed Oil",
    "Cooking Spray | oil spray",
    "Salt | sea salt, cooking salt, salt flakes | @Salt",
    "Black Pepper | pepper, cracked pepper, ground pepper | @Black Pepper",
    "Black Peppercorns | peppercorns, whole peppercorns | @Black Pepper",
    "White Sugar | sugar, caster sugar | @Sugar",
    "Brown Sugar",
    "Icing Sugar",
    "Honey",
    "Maple Syrup",
    "Plain Flour | flour, all purpose flour | @Plain Flour",
    "Self-Raising Flour | self raising flour | @Self-raising Flour",
    "Cornflour | cornstarch | @Cornstarch",
    "Baking Powder",
    "Bicarb Soda | baking soda, bicarbonate of soda | @Bicarbonate Of Soda",
    "Yeast | dried yeast",
    "Vanilla Extract | vanilla",
    "Cocoa Powder | cocoa | @Cocoa",
    "Choc Chips | chocolate chips | @Chocolate Chips",
    "White Rice | rice, long grain rice | @Rice",
    "Jasmine Rice",
    "Basmati Rice",
    "Brown Rice",
    "Arborio Rice | risotto rice | @Paella Rice",
    "Microwave Rice | rice pouch",
    "Spaghetti | spaghetti pasta",
    "Orecchiette | @Farfalle",
    "Penne | penne pasta | @Penne Rigate",
    "Fusilli | spirals, spiral pasta, rotini pasta, rotini | @Farfalle",
    "Rigatoni",
    "Fettuccine | fettuccine pasta",
    "Farfalle | farfalle pasta, bow tie pasta, bowtie pasta | @Bowtie Pasta",
    "Linguine | @Linguine Pasta",
    "Macaroni | elbow pasta",
    "Lasagne Sheets | lasagna sheets, no-boil lasagna noodles, no boil lasagna noodles",
    "Risoni | orzo, orzo pasta | @Vermicelli Pasta",
    "Gnocchi | potato gnocchi",
    "Egg Noodles | hokkien noodles | @Udon Noodles",
    "Rice Noodles | vermicelli noodles, rice vermicelli, flat noodles, flat rice noodles, flat rice pad thai noodles",
    "Udon Noodles",
    "Instant Noodles | 2 minute noodles",
    "Couscous",
    "Quinoa | @Mixed Grain",
    "Rolled Oats | oats, porridge oats",
    "Breakfast Cereal | cereal, weet-bix, cornflakes",
    "Muesli | granola",
    "Panko Breadcrumbs | panko, breadcrumbs, panko bread crumbs | @Breadcrumbs",
    "Chicken Stock | chicken broth, chicken stock pot | @Chicken Stock",
    "Beef Stock | beef broth | @Beef Stock",
    "Vegetable Stock | veggie stock, vegetable broth | @Vegetable Stock",
    "Stock Cubes | stock cube, chicken stock cube | @Chicken Stock Cube",
    "Chicken-Style Stock Powder | chicken stock powder | @Chicken Stock Cube",
    "Vegetable Stock Powder | veggie stock powder, stock powder | @Vegetable Stock Cube",
    "Stock Pot | vegetable stock pot, chicken stock pot, beef stock pot | @Vegetable Stock",
    "Diced Tomatoes | tinned tomatoes, canned tomatoes, crushed tomatoes | @Chopped Tomatoes",
    "Tomato Passata | passata | @Passata",
    "Tomato Paste | tomato puree | @Tomato Puree",
    "Chickpeas | tinned chickpeas, canned chickpeas",
    "Red Kidney Beans | kidney beans | @Kidney Beans",
    "Black Beans | @Pinto Beans",
    "Cannellini Beans | white beans",
    "Brown Lentils | lentils, tinned lentils | @Brown Lentils",
    "Red Lentils | @Green Red Lentils",
    "Baked Beans",
    "Tinned Tuna | tuna, canned tuna | @Tuna",
    "Tinned Corn | corn kernels, sweet corn kernels | @Sweetcorn",
    "Coconut Milk | lite coconut milk",
    "Coconut Cream",
    "Peanut Butter",
    "Vegemite",
    "Jam | strawberry jam, raspberry jam | @Raspberry Jam",
    "Nutella | chocolate spread",
    "Tomato Sauce | ketchup | @Tomato Ketchup",
    "BBQ Sauce | barbecue sauce | @Barbeque Sauce",
    "Mayonnaise | mayo, whole egg mayonnaise",
    "Aioli | garlic aioli, garlic sauce | @Garlic Sauce",
    "Dijon Mustard | mustard",
    "Wholegrain Mustard | seeded mustard | @Mustard",
    "American Mustard | yellow mustard | @Mustard",
    "Worcestershire Sauce",
    "Hot Sauce | tabasco | @Hotsauce",
    "Balsamic Vinegar",
    "White Wine Vinegar | white vinegar, vinegar | @White Vinegar",
    "Red Wine Vinegar",
    "Apple Cider Vinegar",
    "Rice Wine Vinegar | rice vinegar | @Rice Vinegar",
    "Salad Dressing | vinaigrette, creamy pesto dressing, golden goddess dressing, green goddess dressing, balsamic vinaigrette dressing, mustard cider dressing, honey mustard dressing, blue cheese dressing | @Vinaigrette Dressing",
    "Pesto | basil pesto",
    "Pasta Sauce | bolognese sauce, napoletana sauce, marinara sauce, pizza sauce | @Tomato Sauce",
    "Gravy | gravy powder, gravy granules | @Beef Gravy",
    "Capers",
    "Garlic Paste | minced garlic | @Minced Garlic",
    "Ginger Paste | minced ginger",
    "Pepitas | pumpkin seeds",
    "Truffle Oil",
    "Bamboo Shoots",
    "Tamarind Chutney",
    "Babaganoush | baba ganoush, baba ghanoush",
    "Onion Chutney | caramelised onion chutney, onion jam",
    "Burger Sauce",
    "Tartare Sauce | tartar sauce",
    "Chimichurri | chimichurri sauce",
    "Tomato Sugo | sugo | @Passata",
    "Bearnaise Sauce | béarnaise sauce",
    "Duck Fat",
    "Dried Porcini Mushrooms | porcini, porcini powder | @Wild Mushrooms",
    "Pickles | gherkins",
    "Jalapenos | pickled jalapenos | @Jalapeno",
    "Sultanas | raisins",
    "Dried Apricots",
    "Almonds | flaked almonds | @Almonds",
    "Cashews | cashew nuts",
    "Walnuts",
    "Peanuts",
    "Pine Nuts",
    "Pistachios | pistachio nuts",
    "Sesame Seeds | @Sesame Seed",
    "Desiccated Coconut | shredded coconut, shredded unsweetened coconut, unsweetened shredded coconut",
    "Puff Pastry | puff pastry sheets",
    "Shortcrust Pastry",
    "Tahini",
    "Currants",
    "Dried Cranberries | cranberries | @Dried cranberries",
    "Medjool Dates | dates | @Medjool Dates",
    "Filo Pastry | filo, phyllo pastry | @Filo Pastry",
    "Sunflower Seeds",
    "Pecans | pecan halves, pecan nuts | @Pecan Nuts",
    "Freekeh | @Freekeh",
    "Pearl Barley | barley",
    "Polenta | instant polenta, polenta cornmeal, cornmeal",
    "Crunchy Fried Noodles | fried noodles, crispy noodles",
    "Ranch Dressing",
    "Caesar Dressing",
    "Honey Mustard Sauce",
    "Tomato Relish",
    "Gherkin Relish | @Gherkin Relish",
    "Coconut Oil | virgin coconut oil | @Coconut Oil",
    "Artichoke Hearts | marinated artichokes",
    "Nutritional Yeast | nutritional yeast flakes",
    "Alfredo Sauce",
    "Pumpkin Puree | pure pumpkin puree | @Pumpkin Puree",
    "Sauerkraut | @Sauerkraut",
  ],
  "herbs-spices": [
    "Ground Cumin | cumin | @Ground Cumin",
    "Cumin Seeds",
    "Ground Coriander | @Coriander Seeds",
    "Sweet Paprika | paprika | @Paprika",
    "Smoked Paprika",
    "Chilli Powder | chili powder | @Chilli Powder",
    "Chilli Flakes | red chilli flakes, dried chilli flakes | @Red Chilli Flakes",
    "Cayenne Pepper",
    "Ground Turmeric | turmeric | @Turmeric",
    "Ground Cinnamon | cinnamon | @Cinnamon",
    "Cinnamon Stick | cinnamon sticks",
    "Ground Ginger",
    "Nutmeg | ground nutmeg",
    "Garlic Powder | garlic granules, granulated garlic",
    "Onion Powder | @Onion Salt",
    "Dried Oregano | oregano | @Dried Oregano",
    "Dried Thyme | @Thyme",
    "Dried Rosemary | @Rosemary",
    "Dried Basil | @Basil",
    "Italian Herbs | italian seasoning, mixed herbs | @Italian Seasoning",
    "Bay Leaves | bay leaf",
    "Garam Masala",
    "Curry Powder",
    "Ground Cardamom | cardamom",
    "Star Anise",
    "Cloves | whole cloves",
    "Chinese Five Spice | five spice",
    "Fennel Seeds",
    "Mustard Seeds",
    "Celery Salt",
    "Dried Chives | @Chives",
    "Dried Dill | @Dill",
    "Dried Parsley | parsley flakes | @Parsley",
    "Ground Allspice | allspice",
    "Ground Sumac | sumac",
    "Za'atar | zaatar",
    "Cajun Seasoning | cajun spice | @Cajun",
    "Fajita Seasoning | fajita spice mix",
    "Taco Seasoning | taco spice mix | @Fajita Seasoning",
    "Lemon Pepper",
    "Chicken Salt",
    "White Pepper | ground white pepper | @Black Pepper",
    "Dried Mint | @Mint",
    "Ground Sage | dried sage | @Sage",
    "Ground Cloves | @Cloves",
    "Mustard Powder | dry mustard, english mustard powder | @Mustard Powder",
    "Ground Fennel | fennel powder | @Fennel Seeds",
    "Ground Fenugreek | fenugreek | @Fenugreek",
    "Caraway Seeds | ground caraway | @Cumin Seeds",
    "Dried Onion Flakes | onion flakes | @Onion Salt",
    "Coriander Seeds | @Coriander Seeds",
    "Dill Seeds | dill seed | @Dill",
    "Dried Minced Garlic | dehydrated garlic | @Garlic Powder",
    "Dried Marjoram | marjoram | @Marjoram",
    "Poppy Seeds | @Poppy Seeds",
    "Ras El Hanout | @Ras el hanout",
  ],
  international: [
    "Soy Sauce | light soy sauce, salt-reduced soy sauce, soy sauce mix",
    "Dark Soy Sauce",
    "Kecap Manis | sweet soy sauce | @Dark Soy Sauce",
    "Oyster Sauce | plant-based asian mushroom sauce, vegetarian oyster sauce, mushroom sauce",
    "Fish Sauce",
    "Hoisin Sauce | hoisin",
    "Sweet Chilli Sauce | sweet chili sauce",
    "Sriracha | sriracha sauce | @Hotsauce",
    "Teriyaki Sauce | teriyaki",
    "Mirin",
    "Sesame Dressing | japanese dressing, japanese sesame dressing, japanese-style dressing, sesame ginger dressing",
    "Rice Wine | shaoxing wine, chinese cooking wine | @Sake",
    "Miso Paste | miso, white miso",
    "Gochujang | korean chilli paste | @Doubanjiang",
    "Red Curry Paste | thai red curry paste | @Thai Red Curry Paste",
    "Green Curry Paste | thai green curry paste | @Thai Green Curry Paste",
    "Massaman Curry Paste",
    "Katsu Paste | japanese curry paste, golden curry",
    "Tikka Masala Paste | curry paste, korma paste, butter chicken paste | @Madras Paste",
    "Tamarind Paste",
    "Harissa Paste | harissa | @Harissa Spice",
    "Chipotle in Adobo | chipotle paste, chipotle sauce, mild chipotle sauce | @Jalapeno",
    "Salsa | tomato salsa",
    "Enchilada Sauce",
    "Refried Beans",
    "Taco Shells | hard taco shells | @Hard Taco Shells",
    "Rice Paper | rice paper rolls",
    "Nori Sheets | nori, seaweed sheets",
    "Sushi Rice | @Rice",
    "Tofu | firm tofu, silken tofu",
    "Peanut Satay Sauce | satay sauce, peanut sauce | @Peanut Butter",
    "Crispy Shallots | fried shallots | @Shallots",
    "Tortilla Chips | corn chips, nachos",
    "Poppadoms | pappadums",
    "Mango Chutney",
    "Ginger Lemongrass Paste",
    "Tandoori Paste | tandoori curry paste",
    "Stir-Fry Sauce | asian stir-fry sauce, garlic stir-fry sauce, asian stir fry sauce",
    "Chilli Garlic Sauce | chili garlic sauce, chili-garlic sauce",
    "Ponzu | ponzu sauce",
    "Soba Noodles | soba buckwheat noodles, soba",
    "Tempeh",
    "Water Chestnuts | @Water Chestnut",
  ],
  frozen: [
    "Frozen Peas | peas | @Frozen Peas",
    "Frozen Corn | @Sweetcorn",
    "Frozen Mixed Vegetables | frozen veg, mixed veg | @Stir-fry Vegetables",
    "Frozen Berries | mixed berries | @Blueberries",
    "Frozen Chips | chips, oven fries, fries | @Fries",
    "Frozen Edamame | edamame",
    "Frozen Spinach | @Spinach",
    "Ice Cream | vanilla ice cream",
    "Frozen Pizza | pizza",
    "Fish Fingers",
    "Frozen Dumplings | dumplings, gyoza",
    "Frozen Prawns | @Prawns",
    "Hash Browns",
    "Ice | bag of ice",
  ],
  snacks: [
    "Chips (Crisps) | potato chips, crisps, smiths chips",
    "Crackers | rice crackers, water crackers",
    "Chocolate | chocolate block | @Milk Chocolate",
    "Dark Chocolate",
    "Biscuits | cookies, tim tams | @Digestive Biscuits",
    "Muesli Bars | snack bars, granola bars",
    "Popcorn | @Toffee Popcorn",
    "Lollies | sweets, gummies",
    "Pretzels",
    "Mixed Nuts | trail mix | @Cashews",
  ],
  drinks: [
    "Orange Juice | juice, oj",
    "Apple Juice",
    "Sparkling Water | soda water, mineral water",
    "Bottled Water | water | @Water",
    "Soft Drink | coke, lemonade, cola",
    "Coffee Beans | coffee, ground coffee",
    "Instant Coffee",
    "Coffee Pods | capsules, nespresso pods",
    "Tea Bags | tea, black tea, english breakfast",
    "Herbal Tea | green tea, peppermint tea",
    "Cordial | @Ginger Cordial",
    "Kombucha",
    "Beer | @Stout",
    "Red Wine",
    "White Wine | dry white wine",
  ],
  household: [
    "Toilet Paper | toilet rolls, loo paper",
    "Paper Towel | paper towels",
    "Tissues",
    "Dishwashing Liquid | dish soap, detergent",
    "Dishwasher Tablets | dishwasher pods",
    "Laundry Detergent | laundry liquid, washing powder",
    "Fabric Softener",
    "Bin Bags | garbage bags, rubbish bags",
    "Cling Wrap | glad wrap, plastic wrap",
    "Aluminium Foil | foil, alfoil",
    "Baking Paper | parchment paper",
    "Zip Lock Bags | sandwich bags, freezer bags",
    "Sponges | scourers",
    "Surface Spray | cleaner, kitchen spray",
    "Hand Soap | hand wash",
    "Shampoo",
    "Conditioner",
    "Toothpaste",
    "Deodorant",
    "Body Wash | shower gel",
    "Batteries",
  ],
};
